name: Build Node.js Shared Library

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/build_node_shared.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    # container:
    #   image: ghcr.io/ten-framework/ten_building_ubuntu2204
    steps:
      # - name: Checkout Node.js
      #   uses: actions/checkout@v4
      #   with:
      #     repository: nodejs/node
      #     ref: v22.12.0

      # - name: Configure and Build
      #   run: |
      #     if [ "$compiler" == "gcc" ]; then
      #       export CC=gcc
      #       export CXX=g++
      #     else
      #       export CC=clang
      #       export CXX=clang++
      #     fi

      #     ./configure --shared
      #     make -j$(nproc)

      - name: Upload to Google drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: "LICENSE"
          folderId: "aaa"
          name: "node-shared-${{ matrix.compiler }}.zip" # optional string
          overwrite: "true" # optional boolean
