name: Build - win

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "tools/**"
      - "docs/**"
      - ".vscode/**"
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/build_win.yml"
      - "**.md"

jobs:
  build-win-x64:
    concurrency:
      group: build-win-x64-${{ github.head_ref }}-${{ matrix.build_type }}
      cancel-in-progress: true
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [debug, release]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: "true"

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: false

      - name: Install tools and dependencies
        run: |
          pip3 install --use-pep517 python-dotenv jinja2
          go install golang.org/dl/go1.20.12@latest && go1.20.12 download
          go env -w GOFLAGS="-buildvcs=false"
          rustup default nightly
          cargo install --force cbindgen

      - name: Build
        run: |
          $ENV:PATH += ";$PWD/core/ten_gn"
          tgn gen win x64 ${{ matrix.build_type }} -- vs_version=2022 log_level=1 enable_serialized_actions=true ten_enable_integration_tests=false ten_enable_private_tests=false ten_rust_enable_gen_cargo_config=false ten_enable_cargo_clean=true
          tgn build win x64 ${{ matrix.build_type }}

      - name: Run Tests (ten_utils_unit_test)
        env:
          TEN_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/win/x64/tests/standalone/ten_utils_unit_test
          out/win/x64/tests/standalone/ten_utils_unit_test

      - name: Run Tests (ten_runtime_unit_test)
        env:
          TEN_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          chmod +x out/win/x64/tests/standalone/ten_runtime_unit_test
          out/win/x64/tests/standalone/ten_runtime_unit_test

      # - name: Run Tests (ten_runtime_smoke_test)
      #   env:
      #     TEN_ENABLE_BACKTRACE_DUMP: "true"
      #   run: |
      #     chmod +x out/win/x64/tests/standalone/ten_runtime_smoke_test
      #     out/win/x64/tests/standalone/ten_runtime_smoke_test

      - name: Run Tests (ten_rust standalone tests)
        env:
          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          TEN_ENABLE_MEMORY_TRACKING: "true"
          TEN_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          cd out/win/x64/tests/standalone/ten_rust

          chmod +x unit_test
          chmod +x integration_test

          ./unit_test || { echo "ten_rust unit test failed"; exit 1; }
          ./integration_test || { echo "ten_rust integration test failed"; exit 1; }

      - name: Run Tests (ten_manager standalone tests)
        env:
          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
          MALLOC_CHECK_: 3
          TEN_ENABLE_MEMORY_TRACKING: "true"
          TEN_ENABLE_BACKTRACE_DUMP: "true"
        run: |
          cd out/win/x64/tests/standalone/ten_manager

          chmod +x unit_test

          ./unit_test || { echo "ten_manager unit test failed"; exit 1; }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies via script
        run: |
          python .github/tools/setup_pytest_dependencies.py

      - name: Run Tests (ten_manager pytest tests)
        run: |
          pytest -s tests/ten_manager/
