name: Build - docker

on:
  push:
    branches:
      - "**"
    paths:
      - "tools/docker_for_building/**"
      - ".github/workflows/build_docker.yml"

env:
  IMAGE_NAME_PREFIX: ten_building_

jobs:
  build-amd64:
    strategy:
      matrix:
        include:
          - image_name: "ubuntu2204"
            workdir: "tools/docker_for_building/ubuntu/22.04"
          - image_name: "ubuntu1804"
            workdir: "tools/docker_for_building/ubuntu/18.04"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Publish to Github Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository_owner }}/${{ env.IMAGE_NAME_PREFIX }}${{ matrix.image_name }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: ${{ matrix.workdir }}
          platforms: linux/amd64
          snapshot: true
          tags: "${{ github.ref == 'refs/heads/main' && 'latest,' || '' }}"

  build-arm64:
    strategy:
      matrix:
        include:
          - image_name: "ubuntu2204"
            workdir: "tools/docker_for_building/ubuntu/22.04"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Publish to Github Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository_owner }}/${{ env.IMAGE_NAME_PREFIX }}${{ matrix.image_name }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: ${{ matrix.workdir }}
          platforms: linux/arm64
          snapshot: true
          tags: "${{ github.ref == 'refs/heads/main' && 'latest,' || '' }}"
